import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Privacy Policy | Softwala",
    description: "Privacy Policy for Softwala Universal Legal Documents. Learn how we collect, use, and safeguard your information.",
};

export default function PrivacyPolicy() {
    return (
        <div className="min-h-screen bg-zinc-950 text-zinc-300 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-3xl mx-auto space-y-8">
                <header className="border-b border-zinc-800 pb-8">
                    <h1 className="text-3xl font-bold text-white tracking-tight">Privacy Policy</h1>
                    <p className="mt-2 text-sm text-zinc-500">Effective Date: 2026-01-26</p>
                </header>

                <section className="space-y-4">
                    <p>
                        Softwala ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how our mobile applications ("Apps") collect, use, and safeguard your information.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-xl font-semibold text-white">1. Information Collection and Use</h2>

                    <div className="space-y-2">
                        <h3 className="text-lg font-medium text-white/90">1.1. Personal Data</h3>
                        <p>
                            Our Apps are designed to be privacy-first. We do not collect, store, or transmit your personal data (such as name, calendar events, or financial records) to our own servers. All such data is stored locally on your device.
                        </p>
                    </div>

                    <div className="space-y-2">
                        <h3 className="text-lg font-medium text-white/90">1.2. Third-Party Services</h3>
                        <p>We may use third-party services that may collect information used to identify you. These services include:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li><strong className="text-white/80">Google AdMob:</strong> To display advertisements (if applicable). AdMob may use device identifiers to personalize ads.</li>
                            <li><strong className="text-white/80">Google Play Services:</strong> For core app functionality.</li>
                        </ul>
                    </div>

                    <div className="space-y-2">
                        <h3 className="text-lg font-medium text-white/90">1.3. Device Permissions</h3>
                        <p>Our Apps may request specific device permissions to function correctly:</p>
                        <ul className="list-disc pl-5 space-y-1">
                            <li><strong className="text-white/80">Notifications & Alarms:</strong> Used to schedule local reminders for your tasks and events.</li>
                            <li><strong className="text-white/80">Storage/Photos:</strong> Used only if you choose to save or share images generated by the App.</li>
                            <li><strong className="text-white/80">Calendar:</strong> Used to display or sync your local events (if applicable).</li>
                        </ul>
                    </div>
                </section>

                <section className="space-y-4">
                    <h2 className="text-xl font-semibold text-white">2. Data Security</h2>
                    <p>
                        We value your trust in providing us your Personal Information. Since we store data locally on your device, the security of your data relies heavily on the security of your device itself. We recommend keeping your device secure and updated.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-xl font-semibold text-white">3. Changes to This Privacy Policy</h2>
                    <p>
                        We may update our Privacy Policy from time to time. Thus, you are advised to review this page periodically for any changes.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-xl font-semibold text-white">4. Contact Us</h2>
                    <p>
                        If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us at:{" "}
                        <a href="mailto:getsoftwala@gmail.com" className="text-blue-400 hover:text-blue-300 transition-colors">
                            getsoftwala@gmail.com
                        </a>
                    </p>
                </section>
            </div>
        </div>
    );
}
